
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/miaosha ?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource  #?????????
    druid:
      # ???????????????????????
      # ???????????
      initial-size: 500
      min-idle: 500
      max-active: 1000
      # ?????????????
      max-wait: 60000
      # ???????????????????????????????
      time-between-eviction-runs-millis: 60000
      # ??????????????????????
      min-evictable-idle-time-millis: 300000

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    encoding: utf-8
    mode: HTML5
    cache: false
    web:
      resources:
        static-locations: classpath:/static/


mybatis:
  #??sql???????????classpath???resources?
  mapper-locations: classpath:com/example/secondsKill/dao/*.xml
  #??????????????mapper?????????????
  #??type-aliases-package???entity?????mybatis?????????domain
  type-aliases-package: com.example.secondsKill.domain
  configuration:
    # ????uName?????u_name
    map-underscore-to-camel-case: true
    default-statement-timeout: 3000
    default-fetch-size: 100




